import { NextRequest, NextResponse } from 'next/server';
import { getGeminiClient, INGESTION_MODELS, generateWithTimeout } from '@/lib/gemini';
import { INGESTION_SYSTEM_PROMPT } from '@/lib/prompts';
import { MANIFEST_RESPONSE_SCHEMA } from '@/lib/schemas';

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const paperFile = formData.get('paperFile') as File | null;
    const markschemeFile = formData.get('markschemeFile') as File | null;

    if (!paperFile || !markschemeFile) {
      return NextResponse.json(
        { error: 'Both Question Paper and Markscheme PDFs are required.' },
        { status: 400 }
      );
    }

    const clientKey = req.headers.get('x-gemini-key') || undefined;
    const ai = getGeminiClient(clientKey);

    if (!ai) {
      return NextResponse.json(
        { error: 'Gemini API key is missing or not configured.' },
        { status: 401 }
      );
    }

    const paperBuffer = Buffer.from(await paperFile.arrayBuffer());
    const markschemeBuffer = Buffer.from(await markschemeFile.arrayBuffer());

    const paperPart = {
      inlineData: {
        data: paperBuffer.toString('base64'),
        mimeType: 'application/pdf',
      },
    };

    const markschemePart = {
      inlineData: {
        data: markschemeBuffer.toString('base64'),
        mimeType: 'application/pdf',
      },
    };

    const prompt = `Ingest these two official IB examination documents:
Document 1: Official IB Question Paper PDF
Document 2: Matching Official IB Markscheme PDF

CRITICAL INGESTION REQUIREMENTS:
1. Verify the total marks indicated on the cover page (e.g. 110 marks for HL, 90 marks for SL). The sum of all question marks in your output MUST match this total.
2. You MUST extract EVERY question from Section A AND Section B (typically 9 to 12 questions in total). Do NOT stop after Section A or after the first 2 questions.
3. Extract complete exam metadata, subject category (STEM or HUMANITIES), official instructions, grade boundaries, and all questions with exact mark codes (M, A, R, N, AG, FT), page mappings, command terms, syllabus subtopics, and Error Carried Forward (ECF) rules.`;

    let responseText: string | undefined;
    let lastError: unknown;

    for (const modelName of INGESTION_MODELS) {
      try {
        console.log(`Attempting document ingestion with model: ${modelName}...`);
        const response = await generateWithTimeout(
          ai.models.generateContent({
            model: modelName,
            contents: [paperPart, markschemePart, prompt],
            config: {
              systemInstruction: INGESTION_SYSTEM_PROMPT,
              responseMimeType: 'application/json',
              responseSchema: MANIFEST_RESPONSE_SCHEMA,
              temperature: 0.1,
              maxOutputTokens: 65536,
            },
          }),
          120000,
          modelName
        );

        if (response.text) {
          responseText = response.text;
          console.log(`Document ingestion successfully completed using model: ${modelName}`);
          break;
        }
      } catch (err: unknown) {
        lastError = err;
        console.warn(`Ingestion model ${modelName} encountered error, trying fallback...`, err);
        // Wait 500ms before attempting fallback model
        await new Promise((resolve) => setTimeout(resolve, 500));
      }
    }

    if (!responseText) {
      const errMsg = lastError instanceof Error ? lastError.message : 'All Gemini models experienced capacity issues.';
      throw new Error(`Ingestion failed across available models: ${errMsg}`);
    }

    // Resilient JSON parsing (strips any markdown fences if present)
    let cleanText = responseText.trim();
    cleanText = cleanText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();
    const manifestData = JSON.parse(cleanText);
    manifestData.id = `custom-${Date.now()}`;
    manifestData.createdAt = new Date().toISOString();

    // Helper to sanitize SVG markup generated by Gemini
    const sanitizeSvg = (rawSvg?: string | null): string | undefined => {
      if (!rawSvg) return undefined;
      let clean = rawSvg.trim();
      clean = clean.replace(/^```(?:xml|svg|html)?\s*/i, '').replace(/\s*```$/i, '').trim();
      clean = clean.replace(/<\?xml[\s\S]*?\?>/gi, '');
      clean = clean.replace(/<!DOCTYPE[\s\S]*?>/gi, '');
      clean = clean.trim();
      return clean || undefined;
    };

    // Ensure instructions array
    if (!Array.isArray(manifestData.instructions) || manifestData.instructions.length === 0) {
      manifestData.instructions = [
        'A clean copy of the mathematics formula booklet is required for this paper.',
        'Unless otherwise stated in the question, all numerical answers should be given exactly or correct to three significant figures.',
        'Full marks are not necessarily awarded for a correct answer with no working. Answers must be supported by working and/or explanations.',
      ];
    }

    // Normalize question numbers, subparts, SVGs, and re-index pages strictly 1..N containing questions
    if (Array.isArray(manifestData.questions)) {
      const rawPages: number[] = Array.from(
        new Set<number>(
          manifestData.questions.map((q: { pageNumber: number }) => Number(q.pageNumber) || 1)
        )
      ).sort((a: number, b: number) => a - b);

      // If model collapsed all questions to page 1, assign 1 question per page
      const shouldAssignSequentialPages = rawPages.length === 1 && manifestData.questions.length > 1;

      const pageMap = new Map<number, number>();
      rawPages.forEach((origPage: number, idx: number) => {
        pageMap.set(origPage, idx + 1);
      });

      manifestData.questions = manifestData.questions.map((q: {
        id?: string;
        number: string;
        pageNumber: number;
        diagram?: { hasDiagram?: boolean; svgContent?: string; [key: string]: unknown };
        subparts?: Array<{
          id?: string;
          partLetter: string;
          diagram?: { hasDiagram?: boolean; svgContent?: string; [key: string]: unknown };
          [key: string]: unknown;
        }>;
        [key: string]: unknown;
      }, idx: number) => {
        const cleanNumber = q.number.replace(/^Question\s*/i, '').trim();
        const questionId = q.id || `q${idx + 1}`;

        // Sanitize top-level question diagram
        let cleanTopDiagram = undefined;
        if (q.diagram?.hasDiagram) {
          const cleanSvg = sanitizeSvg(q.diagram.svgContent);
          if (cleanSvg) {
            cleanTopDiagram = {
              ...q.diagram,
              hasDiagram: true,
              svgContent: cleanSvg,
            };
          }
        }

        // Sanitize subparts and subpart diagrams
        let normalizedSubparts = undefined;
        if (Array.isArray(q.subparts) && q.subparts.length > 0) {
          normalizedSubparts = q.subparts.map((sub, sIdx) => {
            const cleanLetter = sub.partLetter || `(${String.fromCharCode(97 + sIdx)})`;
            const cleanSuffix = cleanLetter.replace(/[^a-z0-9]/gi, '').toLowerCase() || `${sIdx + 1}`;

            let cleanSubDiagram = undefined;
            if (sub.diagram?.hasDiagram) {
              const cleanSvg = sanitizeSvg(sub.diagram.svgContent);
              if (cleanSvg) {
                cleanSubDiagram = {
                  ...sub.diagram,
                  hasDiagram: true,
                  svgContent: cleanSvg,
                };
              }
            }

            return {
              ...sub,
              id: sub.id || `${questionId}_${cleanSuffix}`,
              partLetter: cleanLetter,
              diagram: cleanSubDiagram,
            };
          });
        }

        const resolvedPage = shouldAssignSequentialPages
          ? idx + 1
          : pageMap.get(Number(q.pageNumber)) || 1;

        return {
          ...q,
          id: questionId,
          number: cleanNumber,
          pageNumber: resolvedPage,
          diagram: cleanTopDiagram,
          subparts: normalizedSubparts,
        };
      });
    }

    return NextResponse.json({ manifest: manifestData });
  } catch (error: unknown) {
    console.error('Ingestion API Error:', error);
    const message = error instanceof Error ? error.message : 'Unknown error during document ingestion.';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
