import { ThinkingLevel } from '@google/genai';
import { getGeminiClient, INGESTION_MODELS, isInvalidKeyError } from '@/lib/gemini';
import { INGESTION_SYSTEM_PROMPT } from '@/lib/prompts';
import { MANIFEST_RESPONSE_SCHEMA } from '@/lib/schemas';
import { parseWithGlmOcr, getZaiApiKey } from '@/lib/ocr/glmOcr';
import { ExamManifest } from '@/types/exam';
import { MissingKeyError } from '@/lib/aiKey';

export interface IngestionOptions {
  geminiKey?: string;
  zaiKey?: string;
  onProgress?: (event: string, details?: unknown) => void;
}

export type IngestionErrorCode = 'INVALID_KEY' | 'MODELS_UNAVAILABLE' | 'UNREADABLE_OUTPUT';

/** A failure the route can explain to the student; the detail stays in `cause` for the server log. */
export class IngestionError extends Error {
  constructor(
    readonly code: IngestionErrorCode,
    message: string,
    options?: { cause?: unknown }
  ) {
    super(message, options);
    this.name = 'IngestionError';
  }
}

/** The whole pipeline stops within this, inside the route's maxDuration of 300 s. */
const PIPELINE_DEADLINE_MS = 270_000;
const MODEL_ATTEMPT_MS = 120_000;

/**
 * Sanitizes and cleans SVG markup generated by Gemini. The SVG is rendered as HTML, and a crafted
 * PDF could steer the model, so anything that can run code or navigate is removed.
 */
export function sanitizeSvg(rawSvg?: string | null): string | undefined {
  if (!rawSvg) return undefined;
  let clean = rawSvg.trim();
  clean = clean.replace(/^```(?:xml|svg|html)?\s*/i, '').replace(/\s*```$/i, '').trim();
  clean = clean.replace(/<\?xml[\s\S]*?\?>/gi, '');
  clean = clean.replace(/<!DOCTYPE[\s\S]*?>/gi, '');
  clean = clean
    .replace(/<(script|foreignObject|iframe|object|embed|style)\b[\s\S]*?<\/\1\s*>/gi, '')
    .replace(/<\/?(script|foreignObject|iframe|object|embed|style|set|animate\w*|a)\b[^>]*>/gi, '')
    .replace(/[\s/]on[a-z]+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, ' ')
    .replace(/\s(?:xlink:)?href\s*=\s*("(?!#)[^"]*"|'(?!#)[^']*'|(?!["'#])[^\s>]+)/gi, '');
  clean = clean.trim();
  return clean || undefined;
}

/**
 * Deep Module: Ingests an official IB examination paper alongside its markscheme,
 * orchestrating parallel GLM-OCR parsing, markscheme binary omission, multi-model fallback racing,
 * SVG graph normalization, and schema validation into an immutable ExamManifest.
 */
export async function compileExamManifest(
  paperBuffer: Buffer,
  markschemeBuffer: Buffer,
  options: IngestionOptions = {}
): Promise<ExamManifest> {
  const deadline = Date.now() + PIPELINE_DEADLINE_MS;
  const notify = (event: string, details?: unknown) => options.onProgress?.(event, details);

  notify('INGEST_START', {
    paperBytes: paperBuffer.length,
    markschemeBytes: markschemeBuffer.length,
  });

  const zaiKey = getZaiApiKey(options.zaiKey);
  const ai = getGeminiClient(options.geminiKey);

  if (!ai) throw new MissingKeyError();

  let glmOcrContext = '';
  let hasMarkschemeOcr = false;

  if (zaiKey) {
    try {
      notify('GLM_OCR_START', 'Dispatching layout parsing for paper & markscheme...');
      const [paperOcr, markschemeOcr] = await Promise.all([
        parseWithGlmOcr(paperBuffer.toString('base64'), 'application/pdf', zaiKey),
        parseWithGlmOcr(markschemeBuffer.toString('base64'), 'application/pdf', zaiKey),
      ]);

      const msMd = markschemeOcr.md_results || '';
      hasMarkschemeOcr = msMd.trim().length > 500;

      glmOcrContext = `\n\n===============================\nGLM-OCR SOTA DOCUMENT RECOGNITION TRANSCRIPT:\n\nDOCUMENT 1 (QUESTION PAPER MARKDOWN):\n${paperOcr.md_results || 'N/A'}\n\nDOCUMENT 2 (MARKSCHEME MARKDOWN):\n${msMd || 'N/A'}\n===============================\nUse this high-precision GLM-OCR extracted Markdown and LaTeX equations to guarantee 100% question extraction accuracy, exact formulas, and correct mark schemes.`;

      notify('GLM_OCR_SUCCESS', {
        paperMarkdownChars: paperOcr.md_results?.length || 0,
        markschemeMarkdownChars: msMd.length,
        omittedMarkschemeBinary: hasMarkschemeOcr,
      });
    } catch (ocrErr) {
      notify('GLM_OCR_WARNING', {
        msg: ocrErr instanceof Error ? ocrErr.message : String(ocrErr),
      });
    }
  }

  const paperPart = {
    inlineData: {
      data: paperBuffer.toString('base64'),
      mimeType: 'application/pdf',
    },
  };

  // When GLM-OCR has already extracted markscheme text, omit binary PDF to avoid redundant rasterization
  const modelContents: unknown[] = [paperPart];
  if (!hasMarkschemeOcr) {
    modelContents.push({
      inlineData: {
        data: markschemeBuffer.toString('base64'),
        mimeType: 'application/pdf',
      },
    });
  }

  const prompt = `Ingest these two official IB examination documents:
Document 1: Official IB Question Paper PDF
Document 2: Matching Official IB Markscheme ${hasMarkschemeOcr ? '(Provided in GLM-OCR transcript above)' : 'PDF'}
${glmOcrContext}

CRITICAL INGESTION REQUIREMENTS:
1. Verify the total marks indicated on the cover page (e.g. 110 marks for HL, 90 marks for SL). The sum of all question marks in your output MUST match this total.
2. You MUST extract EVERY question from Section A AND Section B (typically 9 to 12 questions in total). Do NOT stop after Section A or after the first 2 questions.
3. Extract complete exam metadata, subject category (STEM or HUMANITIES), official instructions, grade boundaries, and all questions with exact mark codes (M, A, R, N, AG, FT), page mappings, command terms, syllabus subtopics, and Error Carried Forward (ECF) rules.`;

  modelContents.push(prompt);

  let responseText: string | undefined;
  let lastError: unknown;

  const deduplicatedModels = Array.from(new Set(INGESTION_MODELS));

  for (const modelName of deduplicatedModels) {
    const remaining = deadline - Date.now();
    if (remaining < 10_000) break;
    try {
      notify('GEMINI_ATTEMPT', {
        model: modelName,
        thinkingLevel: 'low',
        partsCount: modelContents.length,
      });

      const response = await ai.models.generateContent({
        model: modelName,
        contents: modelContents as never,
        config: {
          systemInstruction: INGESTION_SYSTEM_PROMPT,
          responseMimeType: 'application/json',
          responseSchema: MANIFEST_RESPONSE_SCHEMA,
          thinkingConfig: {
            thinkingLevel: ThinkingLevel.LOW,
          },
          temperature: 0.1,
          maxOutputTokens: 65536,
          // Aborts the request itself, not just the wait for it
          abortSignal: AbortSignal.timeout(Math.min(MODEL_ATTEMPT_MS, remaining)),
        },
      });

      if (response.text) {
        responseText = response.text;
        notify('GEMINI_SUCCESS', {
          model: modelName,
          responseChars: response.text.length,
        });
        break;
      }
    } catch (err: unknown) {
      lastError = err;
      if (isInvalidKeyError(err)) {
        throw new IngestionError('INVALID_KEY', 'Gemini rejected the API key.', { cause: err });
      }
      console.warn(`Ingestion model ${modelName} failed, trying the next one:`, err);
      notify('GEMINI_FALLBACK', { model: modelName });
      await new Promise((resolve) => setTimeout(resolve, 500));
    }
  }

  if (!responseText) {
    throw new IngestionError('MODELS_UNAVAILABLE', 'No model could read the PDFs in time.', { cause: lastError });
  }

  const manifestData = parseManifestOutput(responseText);

  notify('INGEST_SUCCESS', {
    manifestId: manifestData.id,
    questions: manifestData.questions.length,
    gradeBoundaries: manifestData.gradeBoundaries,
  });

  return manifestData;
}

/**
 * Turns the model's JSON reply into an Exam Manifest: normalizes question numbers, subparts and
 * SVGs, and re-indexes pages 1..N. Truncated or malformed output throws UNREADABLE_OUTPUT.
 */
export function parseManifestOutput(responseText: string): ExamManifest {
  const unreadable = (message: string, cause?: unknown) =>
    new IngestionError('UNREADABLE_OUTPUT', message, { cause });

  // Resilient JSON parsing (strips any markdown fences if present)
  let cleanText = responseText.trim();
  cleanText = cleanText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();
  let manifestData: ExamManifest;
  try {
    manifestData = JSON.parse(cleanText);
  } catch (err) {
    throw unreadable('The model reply was not complete JSON.', err);
  }
  if (!manifestData || !Array.isArray(manifestData.questions) || manifestData.questions.length === 0) {
    throw unreadable('The model reply had no questions.');
  }
  if (manifestData.questions.some((q) => typeof q?.number !== 'string' || !q.number.trim())) {
    throw unreadable('A question in the model reply had no number.');
  }
  manifestData.id = `custom-${Date.now()}`;
  manifestData.createdAt = new Date().toISOString();

  // Ensure instructions array
  if (!Array.isArray(manifestData.instructions) || manifestData.instructions.length === 0) {
    manifestData.instructions = [
      'A clean copy of the mathematics formula booklet is required for this paper.',
      'Unless otherwise stated in the question, all numerical answers should be given exactly or correct to three significant figures.',
      'Full marks are not necessarily awarded for a correct answer with no working. Answers must be supported by working and/or explanations.',
    ];
  }

  // Normalize question numbers, subparts, SVGs, and re-index pages strictly 1..N containing questions
  if (Array.isArray(manifestData.questions)) {
    const rawPages: number[] = Array.from(
      new Set<number>(
        manifestData.questions.map((q) => Number(q.pageNumber) || 1)
      )
    ).sort((a: number, b: number) => a - b);

    // If model collapsed all questions to page 1, assign 1 question per page
    const shouldAssignSequentialPages = rawPages.length === 1 && manifestData.questions.length > 1;

    const pageMap = new Map<number, number>();
    rawPages.forEach((origPage: number, idx: number) => {
      pageMap.set(origPage, idx + 1);
    });

    manifestData.questions = manifestData.questions.map((q, idx: number) => {
      const cleanNumber = q.number.replace(/^Question\s*/i, '').trim();
      const questionId = q.id || `q${idx + 1}`;

      // Sanitize top-level question diagram
      let cleanTopDiagram = undefined;
      if (q.diagram?.hasDiagram) {
        const cleanSvg = sanitizeSvg(q.diagram.svgContent);
        if (cleanSvg) {
          cleanTopDiagram = {
            ...q.diagram,
            hasDiagram: true,
            svgContent: cleanSvg,
          };
        }
      }

      // Sanitize subparts and subpart diagrams
      let normalizedSubparts = undefined;
      if (Array.isArray(q.subparts) && q.subparts.length > 0) {
        normalizedSubparts = q.subparts.map((sub, sIdx) => {
          const cleanLetter = sub.partLetter || `(${String.fromCharCode(97 + sIdx)})`;
          const cleanSuffix = cleanLetter.replace(/[^a-z0-9]/gi, '').toLowerCase() || `${sIdx + 1}`;

          let cleanSubDiagram = undefined;
          if (sub.diagram?.hasDiagram) {
            const cleanSvg = sanitizeSvg(sub.diagram.svgContent);
            if (cleanSvg) {
              cleanSubDiagram = {
                ...sub.diagram,
                hasDiagram: true,
                svgContent: cleanSvg,
              };
            }
          }

          return {
            ...sub,
            id: sub.id || `${questionId}_${cleanSuffix}`,
            partLetter: cleanLetter,
            diagram: cleanSubDiagram,
          };
        });
      }

      const resolvedPage = shouldAssignSequentialPages
        ? idx + 1
        : pageMap.get(Number(q.pageNumber)) || 1;

      return {
        ...q,
        id: questionId,
        number: cleanNumber,
        pageNumber: resolvedPage,
        diagram: cleanTopDiagram,
        subparts: normalizedSubparts,
      };
    });
  }

  return manifestData;
}
